/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as SiteSettingsRouteImport } from './routes/_site.settings'
import { Route as SiteProfileRouteImport } from './routes/_site.profile'
import { Route as SiteProductsRouteImport } from './routes/_site.products'
import { Route as SiteOrdersRouteImport } from './routes/_site.orders'
import { Route as SiteOrderSuccessRouteImport } from './routes/_site.order-success'
import { Route as SiteCheckoutRouteImport } from './routes/_site.checkout'
import { Route as SiteCartRouteImport } from './routes/_site.cart'
import { Route as Site500RouteImport } from './routes/_site.500'
import { Route as Site403RouteImport } from './routes/_site.403'
import { Route as SiteProductsIdRouteImport } from './routes/_site.products.$id'
import { Route as SiteProductIdRouteImport } from './routes/_site.product.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const SiteSettingsRoute = SiteSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProfileRoute = SiteProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsRoute = SiteProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOrdersRoute = SiteOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOrderSuccessRoute = SiteOrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutRoute = SiteCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCartRoute = SiteCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SiteRoute,
} as any)
const Site500Route = Site500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => SiteRoute,
} as any)
const Site403Route = Site403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsIdRoute = SiteProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SiteProductsRoute,
} as any)
const SiteProductIdRoute = SiteProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/403': typeof Site403Route
  '/500': typeof Site500Route
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/order-success': typeof SiteOrderSuccessRoute
  '/orders': typeof SiteOrdersRoute
  '/products': typeof SiteProductsRouteWithChildren
  '/profile': typeof SiteProfileRoute
  '/settings': typeof SiteSettingsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/product/$id': typeof SiteProductIdRoute
  '/products/$id': typeof SiteProductsIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/403': typeof Site403Route
  '/500': typeof Site500Route
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/order-success': typeof SiteOrderSuccessRoute
  '/orders': typeof SiteOrdersRoute
  '/products': typeof SiteProductsRouteWithChildren
  '/profile': typeof SiteProfileRoute
  '/settings': typeof SiteSettingsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/product/$id': typeof SiteProductIdRoute
  '/products/$id': typeof SiteProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_site/403': typeof Site403Route
  '/_site/500': typeof Site500Route
  '/_site/cart': typeof SiteCartRoute
  '/_site/checkout': typeof SiteCheckoutRoute
  '/_site/order-success': typeof SiteOrderSuccessRoute
  '/_site/orders': typeof SiteOrdersRoute
  '/_site/products': typeof SiteProductsRouteWithChildren
  '/_site/profile': typeof SiteProfileRoute
  '/_site/settings': typeof SiteSettingsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/product/$id': typeof SiteProductIdRoute
  '/_site/products/$id': typeof SiteProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/403'
    | '/500'
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/orders'
    | '/products'
    | '/profile'
    | '/settings'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/admin/'
    | '/product/$id'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/403'
    | '/500'
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/orders'
    | '/products'
    | '/profile'
    | '/settings'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/admin'
    | '/product/$id'
    | '/products/$id'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/auth'
    | '/_site/403'
    | '/_site/500'
    | '/_site/cart'
    | '/_site/checkout'
    | '/_site/order-success'
    | '/_site/orders'
    | '/_site/products'
    | '/_site/profile'
    | '/_site/settings'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/_site/'
    | '/admin/'
    | '/_site/product/$id'
    | '/_site/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/settings': {
      id: '/_site/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SiteSettingsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/profile': {
      id: '/_site/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SiteProfileRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products': {
      id: '/_site/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof SiteProductsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/orders': {
      id: '/_site/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof SiteOrdersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/order-success': {
      id: '/_site/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof SiteOrderSuccessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout': {
      id: '/_site/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof SiteCheckoutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cart': {
      id: '/_site/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SiteCartRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/500': {
      id: '/_site/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof Site500RouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/403': {
      id: '/_site/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof Site403RouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products/$id': {
      id: '/_site/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof SiteProductsIdRouteImport
      parentRoute: typeof SiteProductsRoute
    }
    '/_site/product/$id': {
      id: '/_site/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof SiteProductIdRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteProductsRouteChildren {
  SiteProductsIdRoute: typeof SiteProductsIdRoute
}

const SiteProductsRouteChildren: SiteProductsRouteChildren = {
  SiteProductsIdRoute: SiteProductsIdRoute,
}

const SiteProductsRouteWithChildren = SiteProductsRoute._addFileChildren(
  SiteProductsRouteChildren,
)

interface SiteRouteChildren {
  Site403Route: typeof Site403Route
  Site500Route: typeof Site500Route
  SiteCartRoute: typeof SiteCartRoute
  SiteCheckoutRoute: typeof SiteCheckoutRoute
  SiteOrderSuccessRoute: typeof SiteOrderSuccessRoute
  SiteOrdersRoute: typeof SiteOrdersRoute
  SiteProductsRoute: typeof SiteProductsRouteWithChildren
  SiteProfileRoute: typeof SiteProfileRoute
  SiteSettingsRoute: typeof SiteSettingsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteProductIdRoute: typeof SiteProductIdRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  Site403Route: Site403Route,
  Site500Route: Site500Route,
  SiteCartRoute: SiteCartRoute,
  SiteCheckoutRoute: SiteCheckoutRoute,
  SiteOrderSuccessRoute: SiteOrderSuccessRoute,
  SiteOrdersRoute: SiteOrdersRoute,
  SiteProductsRoute: SiteProductsRouteWithChildren,
  SiteProfileRoute: SiteProfileRoute,
  SiteSettingsRoute: SiteSettingsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteProductIdRoute: SiteProductIdRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
