# analytics/constants.py


class MetricType:
    DASHBOARD = "DASHBOARD"
    ORDER = "ORDER"
    PAYMENT = "PAYMENT"
    PRODUCT = "PRODUCT"
    REVENUE = "REVENUE"
    CUSTOMER = "CUSTOMER"
    RECENT_ORDER = "RECENT_ORDER"
    INVENTORY = "INVENTORY"


class MetricId:
    SUMMARY = "SUMMARY"


class EventType:
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_STATUS_UPDATED = "ORDER_STATUS_UPDATED"
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    PAYMENT_FAILED = "PAYMENT_FAILED"


class OrderStatus:
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    PROCESSING = "PROCESSING"
    SHIPPED = "SHIPPED"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"


class PaymentStatus:
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    CANCELLED = "CANCELLED"


RECENT_ORDERS_LIMIT = 10
TOP_PRODUCTS_LIMIT = 10
